# Generated by Django 3.0.6 on 2020-05-18 03:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('1', 'Language'), ('2', 'Math'), ('3', 'Others')], max_length=1)),
                ('published_date', models.DateTimeField()),
                ('memo', models.TextField(blank=True, max_length=300, null=True)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('memo', models.TextField(blank=True, max_length=300, null=True)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('memo', models.TextField(blank=True, max_length=300, null=True)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('1', 'Requested'), ('2', 'Offered'), ('3', 'Settled'), ('4', 'canceled')], max_length=1)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedbook.BookData')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedbook.Student')),
            ],
        ),
    ]
