# Generated by Django 3.0.6 on 2020-05-18 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdata',
            old_name='bookid',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='bookrequest',
            old_name='bookid',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='bookrequest',
            old_name='studentid',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='bookrequest',
            old_name='uniqueid',
            new_name='unique_id',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='donorid',
            new_name='donor_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentid',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='bookdata',
            name='published_company',
            field=models.CharField(default='bookcompany', max_length=20),
        ),
        migrations.AddField(
            model_name='bookdata',
            name='published_year',
            field=models.CharField(default=1900, max_length=4, validators=[django.core.validators.RegexValidator(regex='(19[0-9]{2}|20[0-9]{2})')]),
            preserve_default=False,
        ),
    ]
