# Generated by Django 3.0.6 on 2020-05-18 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbook', '0004_auto_20200518_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='isbn',
            field=models.CharField(default='4815604967', max_length=13, validators=[django.core.validators.RegexValidator(regex='([0-9]{10})|([0-9]{3}-{10})')]),
        ),
    ]
