# Generated by Django 3.0.6 on 2020-05-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbook', '0006_auto_20200518_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
    ]
