# Generated by Django 3.0.6 on 2020-05-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbook', '0007_auto_20200518_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdata',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='unique_id',
        ),
    ]
